---
- name: Проверка наличия Flux
  command: which flux
  register: flux_check
  failed_when: false
  changed_when: false

- name: Загрузка скрипта установки Flux CLI
  get_url:
    url: https://fluxcd.io/install.sh
    dest: /tmp/install_flux.sh
    mode: "0755"
  hen: flux_check.rc != 0

- name: Установка Flux CLI
  shell: /tmp/install_flux.sh
  when: flux_check.rc != 0

- name: Удаление установочного скрипта Flux CLI
  file:
    path: /tmp/install_flux.sh
    state: absent
  when: flux_check.rc != 0

- name: Проверка версии Flux
  command: flux --version
  register: flux_version
  changed_when: false
