all:
  vars:
    ansible_user: root
    ansible_become: yes
    ansible_become_method: sudo
  hosts:
    k3s_master_KZ:
      ansible_host: 152.152.152.50
    k3s_master_RU:
      ansible_host: 152.152.152.51
