---
- name: Создание .ssh директории для root
  file:
    path: "/root/.ssh"
    state: directory
    owner: "root"
    group: "root"
    mode: "0700"

- name: Добавление SSH ключа для root
  copy:
    src: "{{ type_server }}/files/authorized_keys_root"
    dest: "/root/.ssh/authorized_keys"
    owner: "root"
    group: "root"
    mode: "0600"
  when: lookup('file', '%s/files/authorized_keys_root' % type_server, errors='ignore') is defined
