---
- name: Проверка наличия K3s
  command: which k3s
  register: k3s_check
  failed_when: false
  changed_when: false

- name: Загрузка скрипта установки K3s
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: "0755"
  when: k3s_check.rc != 0

- name: Установка K3s
  shell: /tmp/install_k3s.sh
  when: k3s_check.rc != 0

- name: Удаление установочного скрипта K3s
  file:
    path: /tmp/install_k3s.sh
    state: absent
  when: k3s_check.rc != 0

- name: Запуск и включение K3s
  systemd:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes

- name: Ожидание готовности K3s
  command: systemctl is-active k3s
  register: k3s_status
  until: k3s_status.stdout == "active"
  retries: 30
  delay: 5
  changed_when: false
